from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 391, 321))
        self.groupBox.setObjectName("groupBox")
        self.btn1 = QtWidgets.QPushButton(self.groupBox)
        self.btn1.setGeometry(QtCore.QRect(190, 50, 41, 21))
        self.btn1.setObjectName("btn1")
        self.cmb1 = QtWidgets.QComboBox(self.groupBox)
        self.cmb1.setGeometry(QtCore.QRect(10, 50, 171, 21))
        self.cmb1.setObjectName("cmb1")
        self.lb1 = QtWidgets.QLabel(self.groupBox)
        self.lb1.setGeometry(QtCore.QRect(10, 20, 171, 21))
        self.lb1.setObjectName("lb1")
        self.rdb1 = QtWidgets.QRadioButton(self.groupBox)
        self.rdb1.setGeometry(QtCore.QRect(10, 140, 91, 17))
        self.rdb1.setObjectName("rdb1")
        self.rdb2 = QtWidgets.QRadioButton(self.groupBox)
        self.rdb2.setGeometry(QtCore.QRect(120, 140, 101, 17))
        self.rdb2.setObjectName("rdb2")
        self.rdb3 = QtWidgets.QRadioButton(self.groupBox)
        self.rdb3.setGeometry(QtCore.QRect(230, 140, 111, 17))
        self.rdb3.setObjectName("rdb3")
        self.txt1 = QtWidgets.QTextEdit(self.groupBox)
        self.txt1.setGeometry(QtCore.QRect(20, 170, 331, 131))
        self.txt1.setObjectName("txt1")
        self.lbl3 = QtWidgets.QLabel(self.groupBox)
        self.lbl3.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.lbl3.setObjectName("lbl3")
        self.lbl1 = QtWidgets.QLabel(self.groupBox)
        self.lbl1.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.lbl1.setObjectName("lbl1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 350, 321, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.edt1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.edt1.setGeometry(QtCore.QRect(10, 60, 191, 20))
        self.edt1.setObjectName("edt1")
        self.btn2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn2.setGeometry(QtCore.QRect(210, 60, 41, 23))
        self.btn2.setObjectName("btn2")
        self.lb2 = QtWidgets.QLabel(self.groupBox_2)
        self.lb2.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.lb2.setObjectName("lb2")
        self.btn3 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn3.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.btn3.setObjectName("btn3")
        self.btn4 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn4.setGeometry(QtCore.QRect(110, 100, 75, 23))
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn5.setGeometry(QtCore.QRect(210, 100, 75, 23))
        self.btn5.setObjectName("btn5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archivos Vector"))
        self.groupBox.setTitle(_translate("MainWindow", "Información de Entrada"))
        self.btn1.setText(_translate("MainWindow", "..."))
        self.lb1.setText(_translate("MainWindow", "Selecciona un Archivo Vectorial"))
        self.rdb1.setText(_translate("MainWindow", "Leer Atributos"))
        self.rdb2.setText(_translate("MainWindow", "Editar Atributos"))
        self.rdb3.setText(_translate("MainWindow", "Eliminar Atributos"))
        self.lbl3.setText(_translate("MainWindow", "Centroide"))
        self.lbl1.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Información de Salida"))
        self.btn2.setText(_translate("MainWindow", "..."))
        self.lb2.setText(_translate("MainWindow", "Selecciona la carpeta de Salida"))
        self.btn3.setText(_translate("MainWindow", "Ayuda"))
        self.btn4.setText(_translate("MainWindow", "Ejecutar"))
        self.btn5.setText(_translate("MainWindow", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
